[Feature] Concert 상세보기 및 좋아요 등록하기
Curate-Me/claco-server pull request #53
Opened 2024-11-05 17:42 UTC by anselmo228

## 📌 요약

- 공연 상세보기
![Screenshot 2024-11-06 at 2 41 20 AM](https://github.com/user-attachments/assets/c8e4f134-ef97-4172-8de0-391c5e0cf546)

- 좋아요 등록/취소하기

## 📝 상세 내용

- 공연 상세보기 
-> 기존 공연 정보 + 카테고리 리스트(카테고리명, 이미지 S3 URL)

- 좋아요 등록 및 취소
-> 좋아요가 등록되어 있다면 좋아요 취소로, 좋아요가 등록되지 않았따면 좋아요 생성으로 

## 🗣️ 질문 및 이외 사항

-

### ☑️ 누구에게 리뷰를 요청할까요?

2024-11-05 18:08 UTC, devkeon requested changes

2024-11-05 18:08 UTC, devkeon commented on src/main/java/com/curateme/claco/concert/domain/dto/response/ConcertDetailResponse.java
> +    private List<ConcertCategoryResponse> categories;
이 Response 필드들 필드명이 @Column 안에 있는 이름으로 표시되나요??

2024-11-05 18:08 UTC, devkeon commented on src/main/java/com/curateme/claco/concert/service/ConcertServiceImpl.java
> +            .orElseThrow(() -> new IllegalArgumentException("Concert not found with ID: " + concertLikesRequest.getConcertId()));
여기 BusinessException으로 명시해주면 좋을 것 같습니다! 이러면 응답 코드가 서버 공통 에러로 치환되기 때문에 프론트에서 처리가 어렵습니다!

2024-11-06 04:30 UTC, anselmo228 commented on src/main/java/com/curateme/claco/concert/domain/dto/response/ConcertDetailResponse.java
> +    private List<ConcertCategoryResponse> categories;
스키마로 바꾼다느게 깜빡했습니다..

2024-11-06 04:30 UTC, anselmo228 commented on src/main/java/com/curateme/claco/concert/service/ConcertServiceImpl.java
> +            .orElseThrow(() -> new IllegalArgumentException("Concert not found with ID: " + concertLikesRequest.getConcertId()));
이부분 수정하도록 하겠습니다!

2024-11-06 04:43 UTC, devkeon approved these changes

2024-11-06 04:57 UTC, merged